"""add department contact fields

Revision ID: 0cc7ffd2e2dc
Revises: 4a98bb9dc18e
Create Date: 2026-06-18 17:30:14.711847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc7ffd2e2dc'
down_revision: Union[str, Sequence[str], None] = '4a98bb9dc18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('department_short_name', sa.String(length=100), nullable=True))
    op.add_column('departments', sa.Column('department_email', sa.String(length=255), nullable=True))
    op.add_column('departments', sa.Column('department_phone', sa.String(length=30), nullable=True))
    op.add_column('departments', sa.Column('department_address', sa.String(length=500), nullable=True))
    op.alter_column('departments', 'department_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_departments_department_email'), 'departments', ['department_email'], unique=False)
    op.create_index(op.f('ix_departments_department_phone'), 'departments', ['department_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_department_phone'), table_name='departments')
    op.drop_index(op.f('ix_departments_department_email'), table_name='departments')
    op.alter_column('departments', 'department_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('departments', 'department_address')
    op.drop_column('departments', 'department_phone')
    op.drop_column('departments', 'department_email')
    op.drop_column('departments', 'department_short_name')
    # ### end Alembic commands ###
