"""create audit entity license tables

Revision ID: 120c4a33415d
Revises: 22ed18450280
Create Date: 2026-06-25 23:16:19.398825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120c4a33415d'
down_revision: Union[str, Sequence[str], None] = '22ed18450280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entity_license_types',
    sa.Column('license_type_code', sa.String(length=20), nullable=False),
    sa.Column('license_type_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entity_license_types_id'), 'audit_entity_license_types', ['id'], unique=False)
    op.create_index(op.f('ix_audit_entity_license_types_license_type_code'), 'audit_entity_license_types', ['license_type_code'], unique=True)
    op.create_index(op.f('ix_audit_entity_license_types_license_type_name'), 'audit_entity_license_types', ['license_type_name'], unique=True)
    op.create_table('audit_entity_licenses',
    sa.Column('audit_entity_id', sa.Integer(), nullable=False),
    sa.Column('license_type_id', sa.Integer(), nullable=False),
    sa.Column('license_no', sa.String(length=150), nullable=False),
    sa.Column('license_name', sa.String(length=200), nullable=True),
    sa.Column('issuing_authority', sa.String(length=200), nullable=True),
    sa.Column('issuing_country', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('renewal_due_date', sa.Date(), nullable=True),
    sa.Column('license_status', sa.String(length=30), nullable=False),
    sa.Column('document_reference', sa.String(length=255), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_entity_id'], ['audit_entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['license_type_id'], ['audit_entity_license_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_entity_id', 'license_type_id', 'license_no', name='uq_audit_entity_license_entity_type_no')
    )
    op.create_index(op.f('ix_audit_entity_licenses_audit_entity_id'), 'audit_entity_licenses', ['audit_entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_licenses_expiry_date'), 'audit_entity_licenses', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_audit_entity_licenses_id'), 'audit_entity_licenses', ['id'], unique=False)
    op.create_index(op.f('ix_audit_entity_licenses_issuing_authority'), 'audit_entity_licenses', ['issuing_authority'], unique=False)
    op.create_index(op.f('ix_audit_entity_licenses_license_name'), 'audit_entity_licenses', ['license_name'], unique=False)
    op.create_index(op.f('ix_audit_entity_licenses_license_no'), 'audit_entity_licenses', ['license_no'], unique=False)
    op.create_index(op.f('ix_audit_entity_licenses_license_status'), 'audit_entity_licenses', ['license_status'], unique=False)
    op.create_index(op.f('ix_audit_entity_licenses_license_type_id'), 'audit_entity_licenses', ['license_type_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_licenses_renewal_due_date'), 'audit_entity_licenses', ['renewal_due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_entity_licenses_renewal_due_date'), table_name='audit_entity_licenses')
    op.drop_index(op.f('ix_audit_entity_licenses_license_type_id'), table_name='audit_entity_licenses')
    op.drop_index(op.f('ix_audit_entity_licenses_license_status'), table_name='audit_entity_licenses')
    op.drop_index(op.f('ix_audit_entity_licenses_license_no'), table_name='audit_entity_licenses')
    op.drop_index(op.f('ix_audit_entity_licenses_license_name'), table_name='audit_entity_licenses')
    op.drop_index(op.f('ix_audit_entity_licenses_issuing_authority'), table_name='audit_entity_licenses')
    op.drop_index(op.f('ix_audit_entity_licenses_id'), table_name='audit_entity_licenses')
    op.drop_index(op.f('ix_audit_entity_licenses_expiry_date'), table_name='audit_entity_licenses')
    op.drop_index(op.f('ix_audit_entity_licenses_audit_entity_id'), table_name='audit_entity_licenses')
    op.drop_table('audit_entity_licenses')
    op.drop_index(op.f('ix_audit_entity_license_types_license_type_name'), table_name='audit_entity_license_types')
    op.drop_index(op.f('ix_audit_entity_license_types_license_type_code'), table_name='audit_entity_license_types')
    op.drop_index(op.f('ix_audit_entity_license_types_id'), table_name='audit_entity_license_types')
    op.drop_table('audit_entity_license_types')
    # ### end Alembic commands ###
