"""create audit entity director tables

Revision ID: 22ed18450280
Revises: 2b69dff9eca9
Create Date: 2026-06-25 22:59:18.314933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ed18450280'
down_revision: Union[str, Sequence[str], None] = '2b69dff9eca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entity_director_types',
    sa.Column('director_type_code', sa.String(length=20), nullable=False),
    sa.Column('director_type_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entity_director_types_director_type_code'), 'audit_entity_director_types', ['director_type_code'], unique=True)
    op.create_index(op.f('ix_audit_entity_director_types_director_type_name'), 'audit_entity_director_types', ['director_type_name'], unique=True)
    op.create_index(op.f('ix_audit_entity_director_types_id'), 'audit_entity_director_types', ['id'], unique=False)
    op.create_table('audit_entity_directors',
    sa.Column('audit_entity_id', sa.Integer(), nullable=False),
    sa.Column('director_type_id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=True),
    sa.Column('father_name', sa.String(length=150), nullable=True),
    sa.Column('mother_name', sa.String(length=150), nullable=True),
    sa.Column('spouse_name', sa.String(length=150), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('nid_no', sa.String(length=100), nullable=True),
    sa.Column('passport_no', sa.String(length=100), nullable=True),
    sa.Column('tax_identification_no', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('ownership_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.Column('resignation_date', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_signatory', sa.Boolean(), nullable=False),
    sa.Column('is_beneficial_owner', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_entity_id'], ['audit_entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['director_type_id'], ['audit_entity_director_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entity_directors_audit_entity_id'), 'audit_entity_directors', ['audit_entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_directors_designation'), 'audit_entity_directors', ['designation'], unique=False)
    op.create_index(op.f('ix_audit_entity_directors_director_type_id'), 'audit_entity_directors', ['director_type_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_directors_email'), 'audit_entity_directors', ['email'], unique=False)
    op.create_index(op.f('ix_audit_entity_directors_id'), 'audit_entity_directors', ['id'], unique=False)
    op.create_index(op.f('ix_audit_entity_directors_mobile'), 'audit_entity_directors', ['mobile'], unique=False)
    op.create_index(op.f('ix_audit_entity_directors_nid_no'), 'audit_entity_directors', ['nid_no'], unique=False)
    op.create_index(op.f('ix_audit_entity_directors_passport_no'), 'audit_entity_directors', ['passport_no'], unique=False)
    op.create_index(op.f('ix_audit_entity_directors_person_name'), 'audit_entity_directors', ['person_name'], unique=False)
    op.create_index(op.f('ix_audit_entity_directors_tax_identification_no'), 'audit_entity_directors', ['tax_identification_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_entity_directors_tax_identification_no'), table_name='audit_entity_directors')
    op.drop_index(op.f('ix_audit_entity_directors_person_name'), table_name='audit_entity_directors')
    op.drop_index(op.f('ix_audit_entity_directors_passport_no'), table_name='audit_entity_directors')
    op.drop_index(op.f('ix_audit_entity_directors_nid_no'), table_name='audit_entity_directors')
    op.drop_index(op.f('ix_audit_entity_directors_mobile'), table_name='audit_entity_directors')
    op.drop_index(op.f('ix_audit_entity_directors_id'), table_name='audit_entity_directors')
    op.drop_index(op.f('ix_audit_entity_directors_email'), table_name='audit_entity_directors')
    op.drop_index(op.f('ix_audit_entity_directors_director_type_id'), table_name='audit_entity_directors')
    op.drop_index(op.f('ix_audit_entity_directors_designation'), table_name='audit_entity_directors')
    op.drop_index(op.f('ix_audit_entity_directors_audit_entity_id'), table_name='audit_entity_directors')
    op.drop_table('audit_entity_directors')
    op.drop_index(op.f('ix_audit_entity_director_types_id'), table_name='audit_entity_director_types')
    op.drop_index(op.f('ix_audit_entity_director_types_director_type_name'), table_name='audit_entity_director_types')
    op.drop_index(op.f('ix_audit_entity_director_types_director_type_code'), table_name='audit_entity_director_types')
    op.drop_table('audit_entity_director_types')
    # ### end Alembic commands ###
