"""create audit entity financial snapshot table

Revision ID: 295b95878f61
Revises: 39a15562928b
Create Date: 2026-06-26 17:43:10.028840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295b95878f61'
down_revision: Union[str, Sequence[str], None] = '39a15562928b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entity_financial_snapshots',
    sa.Column('audit_entity_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=20), nullable=False),
    sa.Column('period_start_date', sa.Date(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('statement_type', sa.String(length=30), nullable=False),
    sa.Column('reporting_framework', sa.String(length=100), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('financial_status', sa.String(length=30), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cost_of_sales', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('profit_before_tax', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('profit_after_tax', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cash_and_cash_equivalents', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('inventory', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('trade_receivables', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('trade_payables', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('loans_and_borrowings', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('auditor_name', sa.String(length=200), nullable=True),
    sa.Column('audit_report_date', sa.Date(), nullable=True),
    sa.Column('source_document_reference', sa.String(length=255), nullable=True),
    sa.Column('is_audited', sa.Boolean(), nullable=False),
    sa.Column('is_consolidated', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_entity_id'], ['audit_entities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_entity_id', 'fiscal_year', 'statement_type', name='uq_audit_entity_financial_snapshot_entity_year_type')
    )
    op.create_index(op.f('ix_audit_entity_financial_snapshots_audit_entity_id'), 'audit_entity_financial_snapshots', ['audit_entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_financial_snapshots_currency_code'), 'audit_entity_financial_snapshots', ['currency_code'], unique=False)
    op.create_index(op.f('ix_audit_entity_financial_snapshots_financial_status'), 'audit_entity_financial_snapshots', ['financial_status'], unique=False)
    op.create_index(op.f('ix_audit_entity_financial_snapshots_fiscal_year'), 'audit_entity_financial_snapshots', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_audit_entity_financial_snapshots_id'), 'audit_entity_financial_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_audit_entity_financial_snapshots_period_end_date'), 'audit_entity_financial_snapshots', ['period_end_date'], unique=False)
    op.create_index(op.f('ix_audit_entity_financial_snapshots_reporting_framework'), 'audit_entity_financial_snapshots', ['reporting_framework'], unique=False)
    op.create_index(op.f('ix_audit_entity_financial_snapshots_statement_type'), 'audit_entity_financial_snapshots', ['statement_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_entity_financial_snapshots_statement_type'), table_name='audit_entity_financial_snapshots')
    op.drop_index(op.f('ix_audit_entity_financial_snapshots_reporting_framework'), table_name='audit_entity_financial_snapshots')
    op.drop_index(op.f('ix_audit_entity_financial_snapshots_period_end_date'), table_name='audit_entity_financial_snapshots')
    op.drop_index(op.f('ix_audit_entity_financial_snapshots_id'), table_name='audit_entity_financial_snapshots')
    op.drop_index(op.f('ix_audit_entity_financial_snapshots_fiscal_year'), table_name='audit_entity_financial_snapshots')
    op.drop_index(op.f('ix_audit_entity_financial_snapshots_financial_status'), table_name='audit_entity_financial_snapshots')
    op.drop_index(op.f('ix_audit_entity_financial_snapshots_currency_code'), table_name='audit_entity_financial_snapshots')
    op.drop_index(op.f('ix_audit_entity_financial_snapshots_audit_entity_id'), table_name='audit_entity_financial_snapshots')
    op.drop_table('audit_entity_financial_snapshots')
    # ### end Alembic commands ###
