"""create audit entity contact tables

Revision ID: 2b69dff9eca9
Revises: ba0bfaa150d9
Create Date: 2026-06-25 22:40:28.470265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b69dff9eca9'
down_revision: Union[str, Sequence[str], None] = 'ba0bfaa150d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entity_contact_types',
    sa.Column('contact_type_code', sa.String(length=20), nullable=False),
    sa.Column('contact_type_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entity_contact_types_contact_type_code'), 'audit_entity_contact_types', ['contact_type_code'], unique=True)
    op.create_index(op.f('ix_audit_entity_contact_types_contact_type_name'), 'audit_entity_contact_types', ['contact_type_name'], unique=True)
    op.create_index(op.f('ix_audit_entity_contact_types_id'), 'audit_entity_contact_types', ['id'], unique=False)
    op.create_table('audit_entity_contacts',
    sa.Column('audit_entity_id', sa.Integer(), nullable=False),
    sa.Column('contact_type_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_authorized_representative', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_entity_id'], ['audit_entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contact_type_id'], ['audit_entity_contact_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entity_contacts_audit_entity_id'), 'audit_entity_contacts', ['audit_entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_contacts_contact_name'), 'audit_entity_contacts', ['contact_name'], unique=False)
    op.create_index(op.f('ix_audit_entity_contacts_contact_type_id'), 'audit_entity_contacts', ['contact_type_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_contacts_designation'), 'audit_entity_contacts', ['designation'], unique=False)
    op.create_index(op.f('ix_audit_entity_contacts_email'), 'audit_entity_contacts', ['email'], unique=False)
    op.create_index(op.f('ix_audit_entity_contacts_id'), 'audit_entity_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_audit_entity_contacts_mobile'), 'audit_entity_contacts', ['mobile'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_entity_contacts_mobile'), table_name='audit_entity_contacts')
    op.drop_index(op.f('ix_audit_entity_contacts_id'), table_name='audit_entity_contacts')
    op.drop_index(op.f('ix_audit_entity_contacts_email'), table_name='audit_entity_contacts')
    op.drop_index(op.f('ix_audit_entity_contacts_designation'), table_name='audit_entity_contacts')
    op.drop_index(op.f('ix_audit_entity_contacts_contact_type_id'), table_name='audit_entity_contacts')
    op.drop_index(op.f('ix_audit_entity_contacts_contact_name'), table_name='audit_entity_contacts')
    op.drop_index(op.f('ix_audit_entity_contacts_audit_entity_id'), table_name='audit_entity_contacts')
    op.drop_table('audit_entity_contacts')
    op.drop_index(op.f('ix_audit_entity_contact_types_id'), table_name='audit_entity_contact_types')
    op.drop_index(op.f('ix_audit_entity_contact_types_contact_type_name'), table_name='audit_entity_contact_types')
    op.drop_index(op.f('ix_audit_entity_contact_types_contact_type_code'), table_name='audit_entity_contact_types')
    op.drop_table('audit_entity_contact_types')
    # ### end Alembic commands ###
