"""create audit entity facility tables

Revision ID: 39a15562928b
Revises: 120c4a33415d
Create Date: 2026-06-25 23:39:49.048193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a15562928b'
down_revision: Union[str, Sequence[str], None] = '120c4a33415d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entity_facility_types',
    sa.Column('facility_type_code', sa.String(length=20), nullable=False),
    sa.Column('facility_type_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entity_facility_types_facility_type_code'), 'audit_entity_facility_types', ['facility_type_code'], unique=True)
    op.create_index(op.f('ix_audit_entity_facility_types_facility_type_name'), 'audit_entity_facility_types', ['facility_type_name'], unique=True)
    op.create_index(op.f('ix_audit_entity_facility_types_id'), 'audit_entity_facility_types', ['id'], unique=False)
    op.create_table('audit_entity_facilities',
    sa.Column('audit_entity_id', sa.Integer(), nullable=False),
    sa.Column('facility_type_id', sa.Integer(), nullable=False),
    sa.Column('facility_code', sa.String(length=50), nullable=True),
    sa.Column('facility_name', sa.String(length=200), nullable=False),
    sa.Column('facility_status', sa.String(length=30), nullable=False),
    sa.Column('ownership_type', sa.String(length=30), nullable=True),
    sa.Column('registration_no', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.Text(), nullable=True),
    sa.Column('address_line2', sa.Text(), nullable=True),
    sa.Column('division_code', sa.String(length=50), nullable=True),
    sa.Column('district_code', sa.String(length=50), nullable=True),
    sa.Column('upazila_code', sa.String(length=50), nullable=True),
    sa.Column('post_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('floor_area_sqft', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('production_capacity', sa.String(length=150), nullable=True),
    sa.Column('number_of_employees', sa.Integer(), nullable=True),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_operational', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_entity_id'], ['audit_entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['facility_type_id'], ['audit_entity_facility_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_entity_id', 'facility_type_id', 'facility_name', name='uq_audit_entity_facility_entity_type_name')
    )
    op.create_index(op.f('ix_audit_entity_facilities_audit_entity_id'), 'audit_entity_facilities', ['audit_entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_facilities_city'), 'audit_entity_facilities', ['city'], unique=False)
    op.create_index(op.f('ix_audit_entity_facilities_contact_email'), 'audit_entity_facilities', ['contact_email'], unique=False)
    op.create_index(op.f('ix_audit_entity_facilities_district_code'), 'audit_entity_facilities', ['district_code'], unique=False)
    op.create_index(op.f('ix_audit_entity_facilities_division_code'), 'audit_entity_facilities', ['division_code'], unique=False)
    op.create_index(op.f('ix_audit_entity_facilities_facility_code'), 'audit_entity_facilities', ['facility_code'], unique=False)
    op.create_index(op.f('ix_audit_entity_facilities_facility_name'), 'audit_entity_facilities', ['facility_name'], unique=False)
    op.create_index(op.f('ix_audit_entity_facilities_facility_status'), 'audit_entity_facilities', ['facility_status'], unique=False)
    op.create_index(op.f('ix_audit_entity_facilities_facility_type_id'), 'audit_entity_facilities', ['facility_type_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_facilities_id'), 'audit_entity_facilities', ['id'], unique=False)
    op.create_index(op.f('ix_audit_entity_facilities_ownership_type'), 'audit_entity_facilities', ['ownership_type'], unique=False)
    op.create_index(op.f('ix_audit_entity_facilities_registration_no'), 'audit_entity_facilities', ['registration_no'], unique=False)
    op.create_index(op.f('ix_audit_entity_facilities_upazila_code'), 'audit_entity_facilities', ['upazila_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_entity_facilities_upazila_code'), table_name='audit_entity_facilities')
    op.drop_index(op.f('ix_audit_entity_facilities_registration_no'), table_name='audit_entity_facilities')
    op.drop_index(op.f('ix_audit_entity_facilities_ownership_type'), table_name='audit_entity_facilities')
    op.drop_index(op.f('ix_audit_entity_facilities_id'), table_name='audit_entity_facilities')
    op.drop_index(op.f('ix_audit_entity_facilities_facility_type_id'), table_name='audit_entity_facilities')
    op.drop_index(op.f('ix_audit_entity_facilities_facility_status'), table_name='audit_entity_facilities')
    op.drop_index(op.f('ix_audit_entity_facilities_facility_name'), table_name='audit_entity_facilities')
    op.drop_index(op.f('ix_audit_entity_facilities_facility_code'), table_name='audit_entity_facilities')
    op.drop_index(op.f('ix_audit_entity_facilities_division_code'), table_name='audit_entity_facilities')
    op.drop_index(op.f('ix_audit_entity_facilities_district_code'), table_name='audit_entity_facilities')
    op.drop_index(op.f('ix_audit_entity_facilities_contact_email'), table_name='audit_entity_facilities')
    op.drop_index(op.f('ix_audit_entity_facilities_city'), table_name='audit_entity_facilities')
    op.drop_index(op.f('ix_audit_entity_facilities_audit_entity_id'), table_name='audit_entity_facilities')
    op.drop_table('audit_entity_facilities')
    op.drop_index(op.f('ix_audit_entity_facility_types_id'), table_name='audit_entity_facility_types')
    op.drop_index(op.f('ix_audit_entity_facility_types_facility_type_name'), table_name='audit_entity_facility_types')
    op.drop_index(op.f('ix_audit_entity_facility_types_facility_type_code'), table_name='audit_entity_facility_types')
    op.drop_table('audit_entity_facility_types')
    # ### end Alembic commands ###
