"""add navigation permission mapping tables

Revision ID: 4a98bb9dc18e
Revises: 8f21aa35ff1a
Create Date: 2026-06-14 23:57:20.094608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a98bb9dc18e'
down_revision: Union[str, Sequence[str], None] = '8f21aa35ff1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_permissions',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_permissions_id'), 'menu_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_menu_permissions_menu_id'), 'menu_permissions', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_permissions_permission_id'), 'menu_permissions', ['permission_id'], unique=False)
    op.create_table('menu_action_permissions',
    sa.Column('menu_action_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_action_id'], ['menu_actions.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_action_permissions_id'), 'menu_action_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_menu_action_permissions_menu_action_id'), 'menu_action_permissions', ['menu_action_id'], unique=False)
    op.create_index(op.f('ix_menu_action_permissions_permission_id'), 'menu_action_permissions', ['permission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_action_permissions_permission_id'), table_name='menu_action_permissions')
    op.drop_index(op.f('ix_menu_action_permissions_menu_action_id'), table_name='menu_action_permissions')
    op.drop_index(op.f('ix_menu_action_permissions_id'), table_name='menu_action_permissions')
    op.drop_table('menu_action_permissions')
    op.drop_index(op.f('ix_menu_permissions_permission_id'), table_name='menu_permissions')
    op.drop_index(op.f('ix_menu_permissions_menu_id'), table_name='menu_permissions')
    op.drop_index(op.f('ix_menu_permissions_id'), table_name='menu_permissions')
    op.drop_table('menu_permissions')
    # ### end Alembic commands ###
