"""update employee fields

Revision ID: 4e310701d9b9
Revises: 9af4dc76b584
Create Date: 2026-06-13 22:49:31.225668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e310701d9b9'
down_revision: Union[str, Sequence[str], None] = '9af4dc76b584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('official_employee_id', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('employee_status', sa.String(length=20), nullable=False))
    op.add_column('employees', sa.Column('reporting_to_employee_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.create_index(op.f('ix_employees_official_employee_id'), 'employees', ['official_employee_id'], unique=True)
    op.create_index(op.f('ix_employees_reporting_to_employee_id'), 'employees', ['reporting_to_employee_id'], unique=False)
    op.drop_constraint(op.f('employees_manager_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'employees', ['reporting_to_employee_id'], ['id'])
    op.drop_column('employees', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_manager_id_fkey'), 'employees', 'employees', ['manager_id'], ['id'])
    op.drop_index(op.f('ix_employees_reporting_to_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_official_employee_id'), table_name='employees')
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.drop_column('employees', 'reporting_to_employee_id')
    op.drop_column('employees', 'employee_status')
    op.drop_column('employees', 'official_employee_id')
    # ### end Alembic commands ###
