"""create business master tables

Revision ID: 50e6b1c1c187
Revises: 60eab249ec67
Create Date: 2026-06-25 15:51:18.434717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e6b1c1c187'
down_revision: Union[str, Sequence[str], None] = '60eab249ec67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_natures',
    sa.Column('nature_code', sa.String(length=20), nullable=False),
    sa.Column('nature_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_natures_id'), 'business_natures', ['id'], unique=False)
    op.create_index(op.f('ix_business_natures_nature_code'), 'business_natures', ['nature_code'], unique=True)
    op.create_index(op.f('ix_business_natures_nature_name'), 'business_natures', ['nature_name'], unique=True)
    op.create_table('business_sectors',
    sa.Column('nature_id', sa.Integer(), nullable=False),
    sa.Column('sector_code', sa.String(length=30), nullable=False),
    sa.Column('sector_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nature_id'], ['business_natures.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_sectors_id'), 'business_sectors', ['id'], unique=False)
    op.create_index(op.f('ix_business_sectors_nature_id'), 'business_sectors', ['nature_id'], unique=False)
    op.create_index(op.f('ix_business_sectors_sector_code'), 'business_sectors', ['sector_code'], unique=True)
    op.create_index(op.f('ix_business_sectors_sector_name'), 'business_sectors', ['sector_name'], unique=False)
    op.create_table('business_industries',
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('industry_code', sa.String(length=40), nullable=False),
    sa.Column('industry_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['business_sectors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_industries_id'), 'business_industries', ['id'], unique=False)
    op.create_index(op.f('ix_business_industries_industry_code'), 'business_industries', ['industry_code'], unique=True)
    op.create_index(op.f('ix_business_industries_industry_name'), 'business_industries', ['industry_name'], unique=False)
    op.create_index(op.f('ix_business_industries_sector_id'), 'business_industries', ['sector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_industries_sector_id'), table_name='business_industries')
    op.drop_index(op.f('ix_business_industries_industry_name'), table_name='business_industries')
    op.drop_index(op.f('ix_business_industries_industry_code'), table_name='business_industries')
    op.drop_index(op.f('ix_business_industries_id'), table_name='business_industries')
    op.drop_table('business_industries')
    op.drop_index(op.f('ix_business_sectors_sector_name'), table_name='business_sectors')
    op.drop_index(op.f('ix_business_sectors_sector_code'), table_name='business_sectors')
    op.drop_index(op.f('ix_business_sectors_nature_id'), table_name='business_sectors')
    op.drop_index(op.f('ix_business_sectors_id'), table_name='business_sectors')
    op.drop_table('business_sectors')
    op.drop_index(op.f('ix_business_natures_nature_name'), table_name='business_natures')
    op.drop_index(op.f('ix_business_natures_nature_code'), table_name='business_natures')
    op.drop_index(op.f('ix_business_natures_id'), table_name='business_natures')
    op.drop_table('business_natures')
    # ### end Alembic commands ###
