"""create audit entity exchange listings table

Revision ID: 5332cc61c968
Revises: 72293df6510c
Create Date: 2026-06-25 20:28:03.266660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5332cc61c968'
down_revision: Union[str, Sequence[str], None] = '72293df6510c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entity_exchange_listings',
    sa.Column('audit_entity_id', sa.Integer(), nullable=False),
    sa.Column('listing_code', sa.String(length=50), nullable=False),
    sa.Column('stock_exchange', sa.String(length=30), nullable=False),
    sa.Column('trading_code', sa.String(length=100), nullable=True),
    sa.Column('scrip_code', sa.String(length=100), nullable=True),
    sa.Column('isin_code', sa.String(length=100), nullable=True),
    sa.Column('market_category', sa.String(length=50), nullable=True),
    sa.Column('listed_sector', sa.String(length=150), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('listing_status', sa.String(length=30), nullable=False),
    sa.Column('is_primary_listing', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_entity_id'], ['audit_entities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_entity_id', 'stock_exchange', name='uq_audit_entity_exchange_listing_entity_exchange')
    )
    op.create_index(op.f('ix_audit_entity_exchange_listings_audit_entity_id'), 'audit_entity_exchange_listings', ['audit_entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_exchange_listings_id'), 'audit_entity_exchange_listings', ['id'], unique=False)
    op.create_index(op.f('ix_audit_entity_exchange_listings_listed_sector'), 'audit_entity_exchange_listings', ['listed_sector'], unique=False)
    op.create_index(op.f('ix_audit_entity_exchange_listings_listing_code'), 'audit_entity_exchange_listings', ['listing_code'], unique=True)
    op.create_index(op.f('ix_audit_entity_exchange_listings_listing_status'), 'audit_entity_exchange_listings', ['listing_status'], unique=False)
    op.create_index(op.f('ix_audit_entity_exchange_listings_market_category'), 'audit_entity_exchange_listings', ['market_category'], unique=False)
    op.create_index(op.f('ix_audit_entity_exchange_listings_stock_exchange'), 'audit_entity_exchange_listings', ['stock_exchange'], unique=False)
    op.create_index(op.f('ix_audit_entity_exchange_listings_trading_code'), 'audit_entity_exchange_listings', ['trading_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_entity_exchange_listings_trading_code'), table_name='audit_entity_exchange_listings')
    op.drop_index(op.f('ix_audit_entity_exchange_listings_stock_exchange'), table_name='audit_entity_exchange_listings')
    op.drop_index(op.f('ix_audit_entity_exchange_listings_market_category'), table_name='audit_entity_exchange_listings')
    op.drop_index(op.f('ix_audit_entity_exchange_listings_listing_status'), table_name='audit_entity_exchange_listings')
    op.drop_index(op.f('ix_audit_entity_exchange_listings_listing_code'), table_name='audit_entity_exchange_listings')
    op.drop_index(op.f('ix_audit_entity_exchange_listings_listed_sector'), table_name='audit_entity_exchange_listings')
    op.drop_index(op.f('ix_audit_entity_exchange_listings_id'), table_name='audit_entity_exchange_listings')
    op.drop_index(op.f('ix_audit_entity_exchange_listings_audit_entity_id'), table_name='audit_entity_exchange_listings')
    op.drop_table('audit_entity_exchange_listings')
    # ### end Alembic commands ###
