"""create audit entity business activities table

Revision ID: 5596a801c61b
Revises: db7f1d0df037
Create Date: 2026-06-25 16:40:51.273174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5596a801c61b'
down_revision: Union[str, Sequence[str], None] = 'db7f1d0df037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entity_business_activities',
    sa.Column('audit_entity_id', sa.Integer(), nullable=False),
    sa.Column('activity_code', sa.String(length=50), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('business_nature_id', sa.Integer(), nullable=False),
    sa.Column('business_sector_id', sa.Integer(), nullable=False),
    sa.Column('business_industry_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('risk_rating', sa.String(length=30), nullable=True),
    sa.Column('revenue_percentage', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_entity_id'], ['audit_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_industry_id'], ['business_industries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_nature_id'], ['business_natures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_sector_id'], ['business_sectors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_entity_id', 'business_industry_id', name='uq_audit_entity_business_activity_industry')
    )
    op.create_index(op.f('ix_audit_entity_business_activities_activity_code'), 'audit_entity_business_activities', ['activity_code'], unique=True)
    op.create_index(op.f('ix_audit_entity_business_activities_activity_name'), 'audit_entity_business_activities', ['activity_name'], unique=False)
    op.create_index(op.f('ix_audit_entity_business_activities_audit_entity_id'), 'audit_entity_business_activities', ['audit_entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_business_activities_business_industry_id'), 'audit_entity_business_activities', ['business_industry_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_business_activities_business_nature_id'), 'audit_entity_business_activities', ['business_nature_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_business_activities_business_sector_id'), 'audit_entity_business_activities', ['business_sector_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_business_activities_id'), 'audit_entity_business_activities', ['id'], unique=False)
    op.create_index(op.f('ix_audit_entity_business_activities_risk_rating'), 'audit_entity_business_activities', ['risk_rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_entity_business_activities_risk_rating'), table_name='audit_entity_business_activities')
    op.drop_index(op.f('ix_audit_entity_business_activities_id'), table_name='audit_entity_business_activities')
    op.drop_index(op.f('ix_audit_entity_business_activities_business_sector_id'), table_name='audit_entity_business_activities')
    op.drop_index(op.f('ix_audit_entity_business_activities_business_nature_id'), table_name='audit_entity_business_activities')
    op.drop_index(op.f('ix_audit_entity_business_activities_business_industry_id'), table_name='audit_entity_business_activities')
    op.drop_index(op.f('ix_audit_entity_business_activities_audit_entity_id'), table_name='audit_entity_business_activities')
    op.drop_index(op.f('ix_audit_entity_business_activities_activity_name'), table_name='audit_entity_business_activities')
    op.drop_index(op.f('ix_audit_entity_business_activities_activity_code'), table_name='audit_entity_business_activities')
    op.drop_table('audit_entity_business_activities')
    # ### end Alembic commands ###
