"""create audit entities table

Revision ID: 60eab249ec67
Revises: ae5c45a5da81
Create Date: 2026-06-25 14:53:21.991811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60eab249ec67'
down_revision: Union[str, Sequence[str], None] = 'ae5c45a5da81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entities',
    sa.Column('entity_code', sa.String(length=50), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('registration_no', sa.String(length=100), nullable=True),
    sa.Column('tax_identification_no', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('risk_rating', sa.String(length=30), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entities_entity_code'), 'audit_entities', ['entity_code'], unique=True)
    op.create_index(op.f('ix_audit_entities_entity_name'), 'audit_entities', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_entities_entity_type'), 'audit_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_entities_id'), 'audit_entities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_entities_id'), table_name='audit_entities')
    op.drop_index(op.f('ix_audit_entities_entity_type'), table_name='audit_entities')
    op.drop_index(op.f('ix_audit_entities_entity_name'), table_name='audit_entities')
    op.drop_index(op.f('ix_audit_entities_entity_code'), table_name='audit_entities')
    op.drop_table('audit_entities')
    # ### end Alembic commands ###
