"""add designation short name

Revision ID: 660eb9ae2e48
Revises: 0cc7ffd2e2dc
Create Date: 2026-06-18 22:50:10.741386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660eb9ae2e48'
down_revision: Union[str, Sequence[str], None] = '0cc7ffd2e2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designations', sa.Column('designation_short_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('designations', 'designation_short_name')
    # ### end Alembic commands ###
