"""add companies table

Revision ID: 71e262701578
Revises: 9ec98be59147
Create Date: 2026-06-12 19:36:03.568420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e262701578'
down_revision: Union[str, Sequence[str], None] = '9ec98be59147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_short_name', sa.String(length=100), nullable=True),
    sa.Column('company_email', sa.String(length=255), nullable=True),
    sa.Column('company_phone', sa.String(length=50), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('tax_number', sa.String(length=100), nullable=True),
    sa.Column('trade_license', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_company_code'), 'companies', ['company_code'], unique=True)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_code'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
