"""create legal statuses and link audit entities

Revision ID: 72293df6510c
Revises: 4ec506ba5603
Create Date: 2026-06-25 19:49:01.474925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72293df6510c'
down_revision: Union[str, Sequence[str], None] = '4ec506ba5603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_statuses',
    sa.Column('legal_status_code', sa.String(length=20), nullable=False),
    sa.Column('legal_status_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_statuses_id'), 'legal_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_legal_statuses_legal_status_code'), 'legal_statuses', ['legal_status_code'], unique=True)
    op.create_index(op.f('ix_legal_statuses_legal_status_name'), 'legal_statuses', ['legal_status_name'], unique=True)
    op.add_column('audit_entities', sa.Column('legal_status_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_audit_entities_legal_status_id'), 'audit_entities', ['legal_status_id'], unique=False)
    op.create_foreign_key(None, 'audit_entities', 'legal_statuses', ['legal_status_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_entities', type_='foreignkey')
    op.drop_index(op.f('ix_audit_entities_legal_status_id'), table_name='audit_entities')
    op.drop_column('audit_entities', 'legal_status_id')
    op.drop_index(op.f('ix_legal_statuses_legal_status_name'), table_name='legal_statuses')
    op.drop_index(op.f('ix_legal_statuses_legal_status_code'), table_name='legal_statuses')
    op.drop_index(op.f('ix_legal_statuses_id'), table_name='legal_statuses')
    op.drop_table('legal_statuses')
    # ### end Alembic commands ###
