"""add enterprise navigation tables

Revision ID: 8f21aa35ff1a
Revises: 4e310701d9b9
Create Date: 2026-06-14 23:17:51.443163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f21aa35ff1a'
down_revision: Union[str, Sequence[str], None] = '4e310701d9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navigation_groups',
    sa.Column('group_key', sa.String(length=100), nullable=False),
    sa.Column('group_title', sa.String(length=150), nullable=False),
    sa.Column('group_icon', sa.String(length=100), nullable=True),
    sa.Column('parent_group_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_collapsible', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('group_badge', sa.String(length=50), nullable=True),
    sa.Column('group_color', sa.String(length=50), nullable=True),
    sa.Column('group_permission_key', sa.String(length=150), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['navigation_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_navigation_groups_group_key'), 'navigation_groups', ['group_key'], unique=True)
    op.create_index(op.f('ix_navigation_groups_group_permission_key'), 'navigation_groups', ['group_permission_key'], unique=False)
    op.create_index(op.f('ix_navigation_groups_id'), 'navigation_groups', ['id'], unique=False)
    op.create_index(op.f('ix_navigation_groups_parent_group_id'), 'navigation_groups', ['parent_group_id'], unique=False)
    op.create_table('menus',
    sa.Column('navigation_group_id', sa.Integer(), nullable=True),
    sa.Column('parent_menu_id', sa.Integer(), nullable=True),
    sa.Column('menu_key', sa.String(length=100), nullable=False),
    sa.Column('menu_title', sa.String(length=150), nullable=False),
    sa.Column('route_path', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('permission_key', sa.String(length=150), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('menu_level', sa.Integer(), nullable=False),
    sa.Column('is_expandable', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['navigation_group_id'], ['navigation_groups.id'], ),
    sa.ForeignKeyConstraint(['parent_menu_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=False)
    op.create_index(op.f('ix_menus_menu_key'), 'menus', ['menu_key'], unique=True)
    op.create_index(op.f('ix_menus_navigation_group_id'), 'menus', ['navigation_group_id'], unique=False)
    op.create_index(op.f('ix_menus_parent_menu_id'), 'menus', ['parent_menu_id'], unique=False)
    op.create_index(op.f('ix_menus_permission_key'), 'menus', ['permission_key'], unique=False)
    op.create_table('menu_actions',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('action_key', sa.String(length=100), nullable=False),
    sa.Column('action_title', sa.String(length=100), nullable=False),
    sa.Column('permission_key', sa.String(length=150), nullable=False),
    sa.Column('button_color', sa.String(length=50), nullable=True),
    sa.Column('button_icon', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_actions_action_key'), 'menu_actions', ['action_key'], unique=False)
    op.create_index(op.f('ix_menu_actions_id'), 'menu_actions', ['id'], unique=False)
    op.create_index(op.f('ix_menu_actions_menu_id'), 'menu_actions', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_actions_permission_key'), 'menu_actions', ['permission_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_actions_permission_key'), table_name='menu_actions')
    op.drop_index(op.f('ix_menu_actions_menu_id'), table_name='menu_actions')
    op.drop_index(op.f('ix_menu_actions_id'), table_name='menu_actions')
    op.drop_index(op.f('ix_menu_actions_action_key'), table_name='menu_actions')
    op.drop_table('menu_actions')
    op.drop_index(op.f('ix_menus_permission_key'), table_name='menus')
    op.drop_index(op.f('ix_menus_parent_menu_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_navigation_group_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_menu_key'), table_name='menus')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_navigation_groups_parent_group_id'), table_name='navigation_groups')
    op.drop_index(op.f('ix_navigation_groups_id'), table_name='navigation_groups')
    op.drop_index(op.f('ix_navigation_groups_group_permission_key'), table_name='navigation_groups')
    op.drop_index(op.f('ix_navigation_groups_group_key'), table_name='navigation_groups')
    op.drop_table('navigation_groups')
    # ### end Alembic commands ###
