"""create audit entity tax assessment table

Revision ID: a9f1b99d86b7
Revises: 295b95878f61
Create Date: 2026-06-26 18:44:20.461626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f1b99d86b7'
down_revision: Union[str, Sequence[str], None] = '295b95878f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entity_tax_assessments',
    sa.Column('audit_entity_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.String(length=20), nullable=False),
    sa.Column('assessment_year', sa.String(length=20), nullable=True),
    sa.Column('tax_type', sa.String(length=50), nullable=False),
    sa.Column('tax_identification_no', sa.String(length=100), nullable=True),
    sa.Column('tax_zone', sa.String(length=100), nullable=True),
    sa.Column('tax_circle', sa.String(length=100), nullable=True),
    sa.Column('tax_office', sa.String(length=200), nullable=True),
    sa.Column('return_submission_date', sa.Date(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('demand_notice_date', sa.Date(), nullable=True),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('declared_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('assessed_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('taxable_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tax_payable', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tax_paid', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('outstanding_tax', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('penalty_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('interest_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('assessment_status', sa.String(length=50), nullable=False),
    sa.Column('appeal_status', sa.String(length=50), nullable=True),
    sa.Column('document_reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_entity_id'], ['audit_entities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_entity_id', 'tax_year', 'tax_type', name='uq_audit_entity_tax_assessment_entity_year_type')
    )
    op.create_index(op.f('ix_audit_entity_tax_assessments_appeal_status'), 'audit_entity_tax_assessments', ['appeal_status'], unique=False)
    op.create_index(op.f('ix_audit_entity_tax_assessments_assessment_date'), 'audit_entity_tax_assessments', ['assessment_date'], unique=False)
    op.create_index(op.f('ix_audit_entity_tax_assessments_assessment_status'), 'audit_entity_tax_assessments', ['assessment_status'], unique=False)
    op.create_index(op.f('ix_audit_entity_tax_assessments_assessment_year'), 'audit_entity_tax_assessments', ['assessment_year'], unique=False)
    op.create_index(op.f('ix_audit_entity_tax_assessments_audit_entity_id'), 'audit_entity_tax_assessments', ['audit_entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_tax_assessments_id'), 'audit_entity_tax_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_audit_entity_tax_assessments_payment_due_date'), 'audit_entity_tax_assessments', ['payment_due_date'], unique=False)
    op.create_index(op.f('ix_audit_entity_tax_assessments_tax_circle'), 'audit_entity_tax_assessments', ['tax_circle'], unique=False)
    op.create_index(op.f('ix_audit_entity_tax_assessments_tax_identification_no'), 'audit_entity_tax_assessments', ['tax_identification_no'], unique=False)
    op.create_index(op.f('ix_audit_entity_tax_assessments_tax_type'), 'audit_entity_tax_assessments', ['tax_type'], unique=False)
    op.create_index(op.f('ix_audit_entity_tax_assessments_tax_year'), 'audit_entity_tax_assessments', ['tax_year'], unique=False)
    op.create_index(op.f('ix_audit_entity_tax_assessments_tax_zone'), 'audit_entity_tax_assessments', ['tax_zone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_entity_tax_assessments_tax_zone'), table_name='audit_entity_tax_assessments')
    op.drop_index(op.f('ix_audit_entity_tax_assessments_tax_year'), table_name='audit_entity_tax_assessments')
    op.drop_index(op.f('ix_audit_entity_tax_assessments_tax_type'), table_name='audit_entity_tax_assessments')
    op.drop_index(op.f('ix_audit_entity_tax_assessments_tax_identification_no'), table_name='audit_entity_tax_assessments')
    op.drop_index(op.f('ix_audit_entity_tax_assessments_tax_circle'), table_name='audit_entity_tax_assessments')
    op.drop_index(op.f('ix_audit_entity_tax_assessments_payment_due_date'), table_name='audit_entity_tax_assessments')
    op.drop_index(op.f('ix_audit_entity_tax_assessments_id'), table_name='audit_entity_tax_assessments')
    op.drop_index(op.f('ix_audit_entity_tax_assessments_audit_entity_id'), table_name='audit_entity_tax_assessments')
    op.drop_index(op.f('ix_audit_entity_tax_assessments_assessment_year'), table_name='audit_entity_tax_assessments')
    op.drop_index(op.f('ix_audit_entity_tax_assessments_assessment_status'), table_name='audit_entity_tax_assessments')
    op.drop_index(op.f('ix_audit_entity_tax_assessments_assessment_date'), table_name='audit_entity_tax_assessments')
    op.drop_index(op.f('ix_audit_entity_tax_assessments_appeal_status'), table_name='audit_entity_tax_assessments')
    op.drop_table('audit_entity_tax_assessments')
    # ### end Alembic commands ###
