"""create audit subjects table

Revision ID: ae5c45a5da81
Revises: 18ca3bf94090
Create Date: 2026-06-25 13:11:54.137620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5c45a5da81'
down_revision: Union[str, Sequence[str], None] = '18ca3bf94090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_subjects',
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('owner_department', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('risk_level', sa.String(length=30), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_subjects_id'), 'audit_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_audit_subjects_subject_code'), 'audit_subjects', ['subject_code'], unique=True)
    op.create_index(op.f('ix_audit_subjects_subject_name'), 'audit_subjects', ['subject_name'], unique=False)
    op.create_index(op.f('ix_audit_subjects_subject_type'), 'audit_subjects', ['subject_type'], unique=False)
    op.alter_column('employees', 'employee_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'employee_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_subjects_subject_type'), table_name='audit_subjects')
    op.drop_index(op.f('ix_audit_subjects_subject_name'), table_name='audit_subjects')
    op.drop_index(op.f('ix_audit_subjects_subject_code'), table_name='audit_subjects')
    op.drop_index(op.f('ix_audit_subjects_id'), table_name='audit_subjects')
    op.drop_table('audit_subjects')
    # ### end Alembic commands ###
