"""add exit meeting minutes and snapshot locking

Revision ID: b599332dee15
Revises: 24ecddc8ffc5
Create Date: 2026-07-14 00:25:33.577689
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "b599332dee15"
down_revision: Union[str, Sequence[str], None] = "24ecddc8ffc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "exit_meeting_minutes",
        sa.Column(
            "minute_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "meeting_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "chairman_participant_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "is_locked",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
        sa.Column(
            "locked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "locked_by_user_id",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "template_key",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "template_version",
            sa.String(length=20),
            nullable=True,
        ),
        sa.Column(
            "snapshot_version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column(
            "snapshot_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "snapshot_hash",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "updated_by",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meeting_master.meeting_id"],
            name="fk_exit_meeting_minutes_meeting_id_meeting_master",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["chairman_participant_id"],
            ["meeting_participants.participant_id"],
            name="fk_exit_minute_chairman_participant",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "minute_id",
            name="pk_exit_meeting_minutes",
        ),
    )

    op.create_index(
        "ix_exit_meeting_minutes_minute_id",
        "exit_meeting_minutes",
        ["minute_id"],
        unique=False,
    )
    op.create_index(
        "ix_exit_meeting_minutes_meeting_id",
        "exit_meeting_minutes",
        ["meeting_id"],
        unique=False,
    )
    op.create_index(
        "ix_exit_meeting_minutes_chairman_participant_id",
        "exit_meeting_minutes",
        ["chairman_participant_id"],
        unique=False,
    )
    op.create_index(
        "ix_exit_meeting_minutes_locked_by_user_id",
        "exit_meeting_minutes",
        ["locked_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_exit_meeting_minutes_status",
        "exit_meeting_minutes",
        ["status"],
        unique=False,
    )

    op.add_column(
        "entrance_meeting_minutes",
        sa.Column(
            "is_locked",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
    )
    op.add_column(
        "entrance_meeting_minutes",
        sa.Column(
            "locked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "entrance_meeting_minutes",
        sa.Column(
            "locked_by_user_id",
            sa.String(length=100),
            nullable=True,
        ),
    )
    op.add_column(
        "entrance_meeting_minutes",
        sa.Column(
            "template_key",
            sa.String(length=100),
            nullable=True,
        ),
    )
    op.add_column(
        "entrance_meeting_minutes",
        sa.Column(
            "template_version",
            sa.String(length=20),
            nullable=True,
        ),
    )
    op.add_column(
        "entrance_meeting_minutes",
        sa.Column(
            "snapshot_version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
    )
    op.add_column(
        "entrance_meeting_minutes",
        sa.Column(
            "snapshot_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "entrance_meeting_minutes",
        sa.Column(
            "snapshot_hash",
            sa.String(length=64),
            nullable=True,
        ),
    )

    op.create_index(
        "ix_entrance_meeting_minutes_locked_by_user_id",
        "entrance_meeting_minutes",
        ["locked_by_user_id"],
        unique=False,
    )

    op.add_column(
        "meeting_master",
        sa.Column(
            "audit_id",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_meeting_master_audit_id",
        "meeting_master",
        ["audit_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_meeting_master_audit_id_audit_master",
        "meeting_master",
        "audit_master",
        ["audit_id"],
        ["audit_id"],
        ondelete="RESTRICT",
    )


def downgrade() -> None:
    op.drop_constraint(
        "fk_meeting_master_audit_id_audit_master",
        "meeting_master",
        type_="foreignkey",
    )
    op.drop_index(
        "ix_meeting_master_audit_id",
        table_name="meeting_master",
    )
    op.drop_column(
        "meeting_master",
        "audit_id",
    )

    op.drop_index(
        "ix_entrance_meeting_minutes_locked_by_user_id",
        table_name="entrance_meeting_minutes",
    )
    op.drop_column(
        "entrance_meeting_minutes",
        "snapshot_hash",
    )
    op.drop_column(
        "entrance_meeting_minutes",
        "snapshot_data",
    )
    op.drop_column(
        "entrance_meeting_minutes",
        "snapshot_version",
    )
    op.drop_column(
        "entrance_meeting_minutes",
        "template_version",
    )
    op.drop_column(
        "entrance_meeting_minutes",
        "template_key",
    )
    op.drop_column(
        "entrance_meeting_minutes",
        "locked_by_user_id",
    )
    op.drop_column(
        "entrance_meeting_minutes",
        "locked_at",
    )
    op.drop_column(
        "entrance_meeting_minutes",
        "is_locked",
    )

    op.drop_index(
        "ix_exit_meeting_minutes_status",
        table_name="exit_meeting_minutes",
    )
    op.drop_index(
        "ix_exit_meeting_minutes_locked_by_user_id",
        table_name="exit_meeting_minutes",
    )
    op.drop_index(
        "ix_exit_meeting_minutes_chairman_participant_id",
        table_name="exit_meeting_minutes",
    )
    op.drop_index(
        "ix_exit_meeting_minutes_meeting_id",
        table_name="exit_meeting_minutes",
    )
    op.drop_index(
        "ix_exit_meeting_minutes_minute_id",
        table_name="exit_meeting_minutes",
    )
    op.drop_table(
        "exit_meeting_minutes",
    )


