"""create audit entity address tables

Revision ID: ba0bfaa150d9
Revises: b3689c5c7d95
Create Date: 2026-06-25 22:24:35.359331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0bfaa150d9'
down_revision: Union[str, Sequence[str], None] = 'b3689c5c7d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entity_address_types',
    sa.Column('address_type_code', sa.String(length=20), nullable=False),
    sa.Column('address_type_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entity_address_types_address_type_code'), 'audit_entity_address_types', ['address_type_code'], unique=True)
    op.create_index(op.f('ix_audit_entity_address_types_address_type_name'), 'audit_entity_address_types', ['address_type_name'], unique=True)
    op.create_index(op.f('ix_audit_entity_address_types_id'), 'audit_entity_address_types', ['id'], unique=False)
    op.create_table('audit_entity_addresses',
    sa.Column('audit_entity_id', sa.Integer(), nullable=False),
    sa.Column('address_type_id', sa.Integer(), nullable=False),
    sa.Column('address_line1', sa.Text(), nullable=True),
    sa.Column('address_line2', sa.Text(), nullable=True),
    sa.Column('division_code', sa.String(length=20), nullable=True),
    sa.Column('district_code', sa.String(length=20), nullable=True),
    sa.Column('upazila_code', sa.String(length=20), nullable=True),
    sa.Column('union_code', sa.String(length=20), nullable=True),
    sa.Column('post_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_type_id'], ['audit_entity_address_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['audit_entity_id'], ['audit_entities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_entity_id', 'address_type_id', name='uq_audit_entity_address_entity_type')
    )
    op.create_index(op.f('ix_audit_entity_addresses_address_type_id'), 'audit_entity_addresses', ['address_type_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_addresses_audit_entity_id'), 'audit_entity_addresses', ['audit_entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_addresses_city'), 'audit_entity_addresses', ['city'], unique=False)
    op.create_index(op.f('ix_audit_entity_addresses_id'), 'audit_entity_addresses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_entity_addresses_id'), table_name='audit_entity_addresses')
    op.drop_index(op.f('ix_audit_entity_addresses_city'), table_name='audit_entity_addresses')
    op.drop_index(op.f('ix_audit_entity_addresses_audit_entity_id'), table_name='audit_entity_addresses')
    op.drop_index(op.f('ix_audit_entity_addresses_address_type_id'), table_name='audit_entity_addresses')
    op.drop_table('audit_entity_addresses')
    op.drop_index(op.f('ix_audit_entity_address_types_id'), table_name='audit_entity_address_types')
    op.drop_index(op.f('ix_audit_entity_address_types_address_type_name'), table_name='audit_entity_address_types')
    op.drop_index(op.f('ix_audit_entity_address_types_address_type_code'), table_name='audit_entity_address_types')
    op.drop_table('audit_entity_address_types')
    # ### end Alembic commands ###
