"""add acceptance completion and signoff tables

Revision ID: c266acceptcompletion
Revises: c265acceptactions
Create Date: 2026-07-24
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "c266acceptcompletion"
down_revision: str | None = "c265acceptactions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "audit_accept_completions",
        sa.Column(
            "completion_id",
            sa.Integer(),
            primary_key=True,
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "audit_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "template_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "template_key",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "template_version",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "reference_no",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "file_no",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "workflow_status",
            sa.String(length=40),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "workflow_version",
            sa.Integer(),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "safeguards_text",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "no_safeguard_required",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "acceptance_decision",
            sa.String(length=40),
            nullable=True,
        ),
        sa.Column(
            "conclusion_remarks",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "confirm_relevant_information",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "confirm_independence_evaluated",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "confirm_threats_addressed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "confirm_safeguards_applied",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "confirm_conclusion_documented",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "consultation_required",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "consultation_remarks",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "submitted_by_user_id",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "updated_by",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            """
            workflow_status IN
            (
                'draft',
                'submitted',
                'pending_partner_signoff',
                'pending_consultation',
                'changes_requested',
                'completed',
                'reopened'
            )
            """,
            name=(
                "ck_audit_accept_completions_"
                "workflow_status"
            ),
        ),
        sa.CheckConstraint(
            """
            acceptance_decision IS NULL
            OR acceptance_decision IN
            (
                'accept',
                'accept_with_safeguards',
                'do_not_accept',
                'discontinue'
            )
            """,
            name=(
                "ck_audit_accept_completions_"
                "acceptance_decision"
            ),
        ),
        sa.CheckConstraint(
            "workflow_version >= 1",
            name=(
                "ck_audit_accept_completions_"
                "workflow_version"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["audit_master.audit_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["audit_accept_templates.template_id"],
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "audit_id",
            name=(
                "uq_audit_accept_completions_"
                "audit_id"
            ),
        ),
    )

    op.create_index(
        "ix_audit_accept_completions_template_id",
        "audit_accept_completions",
        ["template_id"],
        unique=False,
    )

    op.create_index(
        (
            "ix_audit_accept_completions_"
            "workflow_status"
        ),
        "audit_accept_completions",
        ["workflow_status"],
        unique=False,
    )

    op.create_table(
        "audit_accept_signoffs",
        sa.Column(
            "signoff_id",
            sa.Integer(),
            primary_key=True,
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "completion_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "signoff_role",
            sa.String(length=40),
            nullable=False,
        ),
        sa.Column(
            "workflow_version",
            sa.Integer(),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "signed_by_user_id",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "signed_by_name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "signed_by_designation",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "declaration_text",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "remarks",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "signed_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "is_current",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "updated_by",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            """
            signoff_role IN
            (
                'engagement_partner',
                'second_partner',
                'quality_reviewer'
            )
            """,
            name=(
                "ck_audit_accept_signoffs_"
                "signoff_role"
            ),
        ),
        sa.CheckConstraint(
            "workflow_version >= 1",
            name=(
                "ck_audit_accept_signoffs_"
                "workflow_version"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["completion_id"],
            [
                "audit_accept_completions."
                "completion_id"
            ],
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "completion_id",
            "signoff_role",
            "workflow_version",
            name=(
                "uq_audit_accept_signoffs_"
                "completion_role_version"
            ),
        ),
    )

    op.create_index(
        "ix_audit_accept_signoffs_completion_id",
        "audit_accept_signoffs",
        ["completion_id"],
        unique=False,
    )

    op.create_index(
        "ix_audit_accept_signoffs_is_current",
        "audit_accept_signoffs",
        ["is_current"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_audit_accept_signoffs_is_current",
        table_name="audit_accept_signoffs",
    )

    op.drop_index(
        "ix_audit_accept_signoffs_completion_id",
        table_name="audit_accept_signoffs",
    )

    op.drop_table("audit_accept_signoffs")

    op.drop_index(
        (
            "ix_audit_accept_completions_"
            "workflow_status"
        ),
        table_name="audit_accept_completions",
    )

    op.drop_index(
        "ix_audit_accept_completions_template_id",
        table_name="audit_accept_completions",
    )

    op.drop_table("audit_accept_completions")
