"""add designations table

Revision ID: c5a98dae9866
Revises: e18759756d8e
Create Date: 2026-06-13 21:59:53.855534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a98dae9866'
down_revision: Union[str, Sequence[str], None] = 'e18759756d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designations',
    sa.Column('designation_code', sa.String(length=50), nullable=False),
    sa.Column('designation_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designations_branch_id'), 'designations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_designations_company_id'), 'designations', ['company_id'], unique=False)
    op.create_index(op.f('ix_designations_department_id'), 'designations', ['department_id'], unique=False)
    op.create_index(op.f('ix_designations_designation_code'), 'designations', ['designation_code'], unique=True)
    op.create_index(op.f('ix_designations_designation_name'), 'designations', ['designation_name'], unique=False)
    op.create_index(op.f('ix_designations_id'), 'designations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_designations_id'), table_name='designations')
    op.drop_index(op.f('ix_designations_designation_name'), table_name='designations')
    op.drop_index(op.f('ix_designations_designation_code'), table_name='designations')
    op.drop_index(op.f('ix_designations_department_id'), table_name='designations')
    op.drop_index(op.f('ix_designations_company_id'), table_name='designations')
    op.drop_index(op.f('ix_designations_branch_id'), table_name='designations')
    op.drop_table('designations')
    # ### end Alembic commands ###
