"""create general_discussion_issue table only

Revision ID: d9a023c30bc8
Revises: c246a1b2c3d4
Create Date: 2026-07-03 00:20:15.994364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9a023c30bc8'
down_revision: Union[str, Sequence[str], None] = 'c246a1b2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_discussion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_discussion_id'), 'general_discussion', ['id'], unique=False)
    op.create_table('general_discussion_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('audit_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_master.audit_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['audit_teams.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_discussion_issue_id'), 'general_discussion_issue', ['id'], unique=False)
    op.drop_index(op.f('idx_general_discussions_report_id'), table_name='general_discussions')
    op.drop_index(op.f('ix_general_discussions_discussion_id'), table_name='general_discussions')
    op.drop_index(op.f('ix_general_discussions_report_id'), table_name='general_discussions')
    op.drop_table('general_discussions')
    op.drop_index(op.f('idx_audit_discussion_issues_audit_type'), table_name='audit_discussion_issues')
    op.drop_index(op.f('idx_audit_discussion_issues_discussion_point'), table_name='audit_discussion_issues')
    op.drop_index(op.f('idx_audit_discussion_issues_status'), table_name='audit_discussion_issues')
    op.create_index(op.f('ix_audit_discussion_issues_audit_type'), 'audit_discussion_issues', ['audit_type'], unique=False)
    op.create_index(op.f('ix_audit_discussion_issues_discussion_point'), 'audit_discussion_issues', ['discussion_point'], unique=False)
    op.create_index(op.f('ix_audit_discussion_issues_status'), 'audit_discussion_issues', ['status'], unique=False)
    op.drop_index(op.f('idx_audit_master_audit_name'), table_name='audit_master')
    op.drop_index(op.f('idx_audit_master_audit_type'), table_name='audit_master')
    op.drop_index(op.f('idx_audit_master_audit_year'), table_name='audit_master')
    op.drop_index(op.f('idx_audit_master_client_id'), table_name='audit_master')
    op.drop_index(op.f('idx_audit_master_status'), table_name='audit_master')
    op.create_index(op.f('ix_audit_master_audit_name'), 'audit_master', ['audit_name'], unique=False)
    op.create_index(op.f('ix_audit_master_audit_type'), 'audit_master', ['audit_type'], unique=False)
    op.create_index(op.f('ix_audit_master_audit_year'), 'audit_master', ['audit_year'], unique=False)
    op.create_index(op.f('ix_audit_master_client_id'), 'audit_master', ['client_id'], unique=False)
    op.create_index(op.f('ix_audit_master_status'), 'audit_master', ['status'], unique=False)
    op.drop_index(op.f('idx_audit_team_members_br_id'), table_name='audit_team_members')
    op.drop_index(op.f('idx_audit_team_members_client_contact_id'), table_name='audit_team_members')
    op.drop_index(op.f('idx_audit_team_members_client_id'), table_name='audit_team_members')
    op.drop_index(op.f('idx_audit_team_members_emp_id'), table_name='audit_team_members')
    op.drop_index(op.f('idx_audit_team_members_member_type'), table_name='audit_team_members')
    op.drop_index(op.f('idx_audit_team_members_status'), table_name='audit_team_members')
    op.drop_index(op.f('idx_audit_team_members_team_id'), table_name='audit_team_members')
    op.create_index(op.f('ix_audit_team_members_br_id'), 'audit_team_members', ['br_id'], unique=False)
    op.create_index(op.f('ix_audit_team_members_client_contact_id'), 'audit_team_members', ['client_contact_id'], unique=False)
    op.create_index(op.f('ix_audit_team_members_client_id'), 'audit_team_members', ['client_id'], unique=False)
    op.create_index(op.f('ix_audit_team_members_emp_id'), 'audit_team_members', ['emp_id'], unique=False)
    op.create_index(op.f('ix_audit_team_members_member_type'), 'audit_team_members', ['member_type'], unique=False)
    op.create_index(op.f('ix_audit_team_members_status'), 'audit_team_members', ['status'], unique=False)
    op.create_index(op.f('ix_audit_team_members_team_id'), 'audit_team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_audit_team_members_team_member_role'), 'audit_team_members', ['team_member_role'], unique=False)
    op.drop_index(op.f('idx_audit_teams_status'), table_name='audit_teams')
    op.drop_index(op.f('idx_audit_teams_team_name'), table_name='audit_teams')
    op.create_index(op.f('ix_audit_teams_status'), 'audit_teams', ['status'], unique=False)
    op.create_index(op.f('ix_audit_teams_team_name'), 'audit_teams', ['team_name'], unique=False)
    op.drop_index(op.f('idx_audit_visit_info_audit_id'), table_name='audit_visit_info')
    op.drop_index(op.f('idx_audit_visit_info_client_address_id'), table_name='audit_visit_info')
    op.drop_index(op.f('idx_audit_visit_info_status'), table_name='audit_visit_info')
    op.drop_index(op.f('idx_audit_visit_info_team_id'), table_name='audit_visit_info')
    op.drop_index(op.f('idx_audit_visit_info_visit_date'), table_name='audit_visit_info')
    op.create_index(op.f('ix_audit_visit_info_audit_id'), 'audit_visit_info', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_visit_info_client_address_id'), 'audit_visit_info', ['client_address_id'], unique=False)
    op.create_index(op.f('ix_audit_visit_info_status'), 'audit_visit_info', ['status'], unique=False)
    op.create_index(op.f('ix_audit_visit_info_team_id'), 'audit_visit_info', ['team_id'], unique=False)
    op.create_index(op.f('ix_audit_visit_info_visit_date'), 'audit_visit_info', ['visit_date'], unique=False)
    op.drop_index(op.f('idx_audit_visit_observations_audit_id'), table_name='audit_visit_observations')
    op.drop_index(op.f('idx_audit_visit_observations_audit_type'), table_name='audit_visit_observations')
    op.drop_index(op.f('idx_audit_visit_observations_issue_id'), table_name='audit_visit_observations')
    op.drop_index(op.f('idx_audit_visit_observations_status'), table_name='audit_visit_observations')
    op.drop_index(op.f('idx_audit_visit_observations_team_id'), table_name='audit_visit_observations')
    op.drop_index(op.f('idx_audit_visit_observations_visit_id'), table_name='audit_visit_observations')
    op.create_index(op.f('ix_audit_visit_observations_audit_id'), 'audit_visit_observations', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_visit_observations_audit_type'), 'audit_visit_observations', ['audit_type'], unique=False)
    op.create_index(op.f('ix_audit_visit_observations_discussion_point'), 'audit_visit_observations', ['discussion_point'], unique=False)
    op.create_index(op.f('ix_audit_visit_observations_issue_id'), 'audit_visit_observations', ['issue_id'], unique=False)
    op.create_index(op.f('ix_audit_visit_observations_status'), 'audit_visit_observations', ['status'], unique=False)
    op.create_index(op.f('ix_audit_visit_observations_team_id'), 'audit_visit_observations', ['team_id'], unique=False)
    op.create_index(op.f('ix_audit_visit_observations_visit_id'), 'audit_visit_observations', ['visit_id'], unique=False)
    op.drop_index(op.f('idx_auditor_work_plan_report_id'), table_name='auditor_work_plan')
    op.drop_index(op.f('idx_business_discussions_report_id'), table_name='business_discussions')
    op.drop_index(op.f('idx_cooperation_agreement_report_id'), table_name='cooperation_agreement')
    op.drop_index(op.f('idx_meeting_master_type_client_code_date'), table_name='meeting_master')
    op.drop_index(op.f('idx_participants_report_id'), table_name='meeting_participants')
    op.drop_index(op.f('idx_meeting_reports_type_client_date'), table_name='meeting_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_meeting_reports_type_client_date'), 'meeting_reports', ['meeting_type', 'client_name', 'meeting_date'], unique=False)
    op.create_index(op.f('idx_participants_report_id'), 'meeting_participants', ['report_id'], unique=False)
    op.create_index(op.f('idx_meeting_master_type_client_code_date'), 'meeting_master', ['meeting_type', 'client_id', 'client_code', 'meeting_date'], unique=False)
    op.create_index(op.f('idx_cooperation_agreement_report_id'), 'cooperation_agreement', ['report_id'], unique=False)
    op.create_index(op.f('idx_business_discussions_report_id'), 'business_discussions', ['report_id'], unique=False)
    op.create_index(op.f('idx_auditor_work_plan_report_id'), 'auditor_work_plan', ['report_id'], unique=False)
    op.drop_index(op.f('ix_audit_visit_observations_visit_id'), table_name='audit_visit_observations')
    op.drop_index(op.f('ix_audit_visit_observations_team_id'), table_name='audit_visit_observations')
    op.drop_index(op.f('ix_audit_visit_observations_status'), table_name='audit_visit_observations')
    op.drop_index(op.f('ix_audit_visit_observations_issue_id'), table_name='audit_visit_observations')
    op.drop_index(op.f('ix_audit_visit_observations_discussion_point'), table_name='audit_visit_observations')
    op.drop_index(op.f('ix_audit_visit_observations_audit_type'), table_name='audit_visit_observations')
    op.drop_index(op.f('ix_audit_visit_observations_audit_id'), table_name='audit_visit_observations')
    op.create_index(op.f('idx_audit_visit_observations_visit_id'), 'audit_visit_observations', ['visit_id'], unique=False)
    op.create_index(op.f('idx_audit_visit_observations_team_id'), 'audit_visit_observations', ['team_id'], unique=False)
    op.create_index(op.f('idx_audit_visit_observations_status'), 'audit_visit_observations', ['status'], unique=False)
    op.create_index(op.f('idx_audit_visit_observations_issue_id'), 'audit_visit_observations', ['issue_id'], unique=False)
    op.create_index(op.f('idx_audit_visit_observations_audit_type'), 'audit_visit_observations', ['audit_type'], unique=False)
    op.create_index(op.f('idx_audit_visit_observations_audit_id'), 'audit_visit_observations', ['audit_id'], unique=False)
    op.drop_index(op.f('ix_audit_visit_info_visit_date'), table_name='audit_visit_info')
    op.drop_index(op.f('ix_audit_visit_info_team_id'), table_name='audit_visit_info')
    op.drop_index(op.f('ix_audit_visit_info_status'), table_name='audit_visit_info')
    op.drop_index(op.f('ix_audit_visit_info_client_address_id'), table_name='audit_visit_info')
    op.drop_index(op.f('ix_audit_visit_info_audit_id'), table_name='audit_visit_info')
    op.create_index(op.f('idx_audit_visit_info_visit_date'), 'audit_visit_info', ['visit_date'], unique=False)
    op.create_index(op.f('idx_audit_visit_info_team_id'), 'audit_visit_info', ['team_id'], unique=False)
    op.create_index(op.f('idx_audit_visit_info_status'), 'audit_visit_info', ['status'], unique=False)
    op.create_index(op.f('idx_audit_visit_info_client_address_id'), 'audit_visit_info', ['client_address_id'], unique=False)
    op.create_index(op.f('idx_audit_visit_info_audit_id'), 'audit_visit_info', ['audit_id'], unique=False)
    op.drop_index(op.f('ix_audit_teams_team_name'), table_name='audit_teams')
    op.drop_index(op.f('ix_audit_teams_status'), table_name='audit_teams')
    op.create_index(op.f('idx_audit_teams_team_name'), 'audit_teams', ['team_name'], unique=False)
    op.create_index(op.f('idx_audit_teams_status'), 'audit_teams', ['status'], unique=False)
    op.drop_index(op.f('ix_audit_team_members_team_member_role'), table_name='audit_team_members')
    op.drop_index(op.f('ix_audit_team_members_team_id'), table_name='audit_team_members')
    op.drop_index(op.f('ix_audit_team_members_status'), table_name='audit_team_members')
    op.drop_index(op.f('ix_audit_team_members_member_type'), table_name='audit_team_members')
    op.drop_index(op.f('ix_audit_team_members_emp_id'), table_name='audit_team_members')
    op.drop_index(op.f('ix_audit_team_members_client_id'), table_name='audit_team_members')
    op.drop_index(op.f('ix_audit_team_members_client_contact_id'), table_name='audit_team_members')
    op.drop_index(op.f('ix_audit_team_members_br_id'), table_name='audit_team_members')
    op.create_index(op.f('idx_audit_team_members_team_id'), 'audit_team_members', ['team_id'], unique=False)
    op.create_index(op.f('idx_audit_team_members_status'), 'audit_team_members', ['status'], unique=False)
    op.create_index(op.f('idx_audit_team_members_member_type'), 'audit_team_members', ['member_type'], unique=False)
    op.create_index(op.f('idx_audit_team_members_emp_id'), 'audit_team_members', ['emp_id'], unique=False)
    op.create_index(op.f('idx_audit_team_members_client_id'), 'audit_team_members', ['client_id'], unique=False)
    op.create_index(op.f('idx_audit_team_members_client_contact_id'), 'audit_team_members', ['client_contact_id'], unique=False)
    op.create_index(op.f('idx_audit_team_members_br_id'), 'audit_team_members', ['br_id'], unique=False)
    op.drop_index(op.f('ix_audit_master_status'), table_name='audit_master')
    op.drop_index(op.f('ix_audit_master_client_id'), table_name='audit_master')
    op.drop_index(op.f('ix_audit_master_audit_year'), table_name='audit_master')
    op.drop_index(op.f('ix_audit_master_audit_type'), table_name='audit_master')
    op.drop_index(op.f('ix_audit_master_audit_name'), table_name='audit_master')
    op.create_index(op.f('idx_audit_master_status'), 'audit_master', ['status'], unique=False)
    op.create_index(op.f('idx_audit_master_client_id'), 'audit_master', ['client_id'], unique=False)
    op.create_index(op.f('idx_audit_master_audit_year'), 'audit_master', ['audit_year'], unique=False)
    op.create_index(op.f('idx_audit_master_audit_type'), 'audit_master', ['audit_type'], unique=False)
    op.create_index(op.f('idx_audit_master_audit_name'), 'audit_master', ['audit_name'], unique=False)
    op.drop_index(op.f('ix_audit_discussion_issues_status'), table_name='audit_discussion_issues')
    op.drop_index(op.f('ix_audit_discussion_issues_discussion_point'), table_name='audit_discussion_issues')
    op.drop_index(op.f('ix_audit_discussion_issues_audit_type'), table_name='audit_discussion_issues')
    op.create_index(op.f('idx_audit_discussion_issues_status'), 'audit_discussion_issues', ['status'], unique=False)
    op.create_index(op.f('idx_audit_discussion_issues_discussion_point'), 'audit_discussion_issues', ['discussion_point'], unique=False)
    op.create_index(op.f('idx_audit_discussion_issues_audit_type'), 'audit_discussion_issues', ['audit_type'], unique=False)
    op.create_table('general_discussions',
    sa.Column('discussion_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discussion_point', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('decision', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['meeting_reports.report_id'], name=op.f('general_discussions_report_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('discussion_id', name=op.f('general_discussions_pkey'))
    )
    op.create_index(op.f('ix_general_discussions_report_id'), 'general_discussions', ['report_id'], unique=False)
    op.create_index(op.f('ix_general_discussions_discussion_id'), 'general_discussions', ['discussion_id'], unique=False)
    op.create_index(op.f('idx_general_discussions_report_id'), 'general_discussions', ['report_id'], unique=False)
    op.drop_index(op.f('ix_general_discussion_issue_id'), table_name='general_discussion_issue')
    op.drop_table('general_discussion_issue')
    op.drop_index(op.f('ix_general_discussion_id'), table_name='general_discussion')
    op.drop_table('general_discussion')
    # ### end Alembic commands ###
