"""add business master references to audit entities

Revision ID: db7f1d0df037
Revises: 50e6b1c1c187
Create Date: 2026-06-25 16:01:54.890487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7f1d0df037'
down_revision: Union[str, Sequence[str], None] = '50e6b1c1c187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_entities', sa.Column('business_nature_id', sa.Integer(), nullable=True))
    op.add_column('audit_entities', sa.Column('business_sector_id', sa.Integer(), nullable=True))
    op.add_column('audit_entities', sa.Column('business_industry_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_audit_entities_business_industry_id'), 'audit_entities', ['business_industry_id'], unique=False)
    op.create_index(op.f('ix_audit_entities_business_nature_id'), 'audit_entities', ['business_nature_id'], unique=False)
    op.create_index(op.f('ix_audit_entities_business_sector_id'), 'audit_entities', ['business_sector_id'], unique=False)
    op.create_foreign_key(None, 'audit_entities', 'business_industries', ['business_industry_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'audit_entities', 'business_sectors', ['business_sector_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'audit_entities', 'business_natures', ['business_nature_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_entities', type_='foreignkey')
    op.drop_constraint(None, 'audit_entities', type_='foreignkey')
    op.drop_constraint(None, 'audit_entities', type_='foreignkey')
    op.drop_index(op.f('ix_audit_entities_business_sector_id'), table_name='audit_entities')
    op.drop_index(op.f('ix_audit_entities_business_nature_id'), table_name='audit_entities')
    op.drop_index(op.f('ix_audit_entities_business_industry_id'), table_name='audit_entities')
    op.drop_column('audit_entities', 'business_industry_id')
    op.drop_column('audit_entities', 'business_sector_id')
    op.drop_column('audit_entities', 'business_nature_id')
    # ### end Alembic commands ###
